# ==============================================================
# WAX CONFIGURATION
# ==============================================================
# Jekyll configuration files are written in YAML format.
# Colons, tabs/spacing, and quotes are meaningful in YAML.
# It is recommended you look at the following guide to avoid
# syntax errors in this file:
# ~> https://learnxinyminutes.com/docs/yaml/
#
#
# Questions ?
# ~> https://minicomp.github.io/wiki/#/
#
# ---------------------------------------------------------------
# MAIN SETTINGS
# ---------------------------------------------------------------
# Feel free to change these! For more info, refer to:
# ~> https://jekyllrb.com/docs/configuration/options/

title:            'El Club de los Cómics Perdidos'
description:      'Archivo de cómic colombiano'
url:              'https://gestionmojicon100.github.io'
baseurl:          '/comicsperdidos'
copyright:        'Año 99 Cómic Colombiano, 2023'
logo:             '/assets/LogoA99.png'
default_thumb:    '/assets/LogoA99.png'

# ---------------------------------------------------------------
# BUILD SETTINGS
# ---------------------------------------------------------------
# Best not to mess with these unless you know what you're doing!

permalink: 'pretty'
sass:
  style: compressed
exclude: ["Gemfile*", "*.gemspec", "Rakefile", "vendor", "spec", "README.md", "LICENSE.txt", "Docker*"]
webrick:
  headers:
    'Access-Control-Allow-Origin': '*'
kramdown:
 auto_ids:       true
 footnote_nr:    1
 entity_output:  as_char
 footnote_backlink: "&#x21a9;&#xfe0e;"
 toc_levels:     1..6
 smart_quotes:   lsquo,rsquo,ldquo,rdquo
 enable_coderay: false


# --------------------------------------------------------------
# COLLECTION SETTINGS
# --------------------------------------------------------------
# Wax leverages Jekyll collections for much of its
# functionality, therefor some of the keys below are from
# Jekyll while others are Wax-specific.
# For more info, refer to:
# ~> https://jekyllrb.com/docs/collections/

collections:
  exhibits:
    output: true
  comics: # name of collection
    output: true # makes sure pages are output as html files
    layout: 'comic_item' # the layout for the pages to use
    metadata:
      source: 'comics.csv' # path to the metadata file within `_data`
    images:
      source: 'raw_images/comics' # path to the directory of images within `_data`

# --------------------------------------------------------------
# SEARCH INDEX SETTINGS
# --------------------------------------------------------------
# You can create multiple search indexes below (though only one is
# recommended!) by specifying
# an `index` file to write it to and some `collections` for it to index
# and running `$ bundle exec rake wax:search` .

search:
  main:
    index: '/search/index.json' # file the index will get written to
    collections:
      comics:
        content: false # whether or not to index page content
        fields: # the metadata fields to index
          - label
          - nombre_completo

# --------------------------------------------------------------
# SITE MENU SETTINGS
# --------------------------------------------------------------
# Each menu item needs a `label` (whats shown), and a `link`
# (where it goes). An item can optionally have a dropdown
# submenu via `sub`.

menu:
  - label: 'Acerca'
    link: '/about/'
  - label: 'Explorar'
    sub:
      - label: 'Por autor'
        link: 'collection_author'
      - label: 'Por fecha'
        link: 'collection_date'
      - label: 'Por categoría'
        link: 'collection_category'
  - label: 'Buscador'
    link: '/search/'
  - label: 'Muestras'
    sub:
      - label: 'Personajes'
        link: '/exhibits/personajes/'

# --------------------------------------------------------------
# SITE FOOTER SETTINGS
# --------------------------------------------------------------
#

footer:
  links:
    - label: 'Créditos'
      link: '/credits'
    - label: 'Metadatos'
      link: '/reuse'
  logos:
    - label: 'A99'
      img: '/img/LogoA99.png'
    - label: 'ComicsPerdidos'
      img: '/img/LogoComicsPerdidos.png'

# FIN